server:
  port: 9999

spring:
  profiles:
    active: local

  config:
    import: optional:classpath:configs/${spring.profiles.active}/db-config.yml


application-name: product-service

security:
  password:
    expiry-minutes: 10


  # For dev
  # mvn spring-boot:run -Dspring-boot.run.profiles=dev


  # For prod
  # mvn spring-boot:run -Dspring-boot.run.profiles=prod




