spring:
  datasource:
    url: jdbc:mysql://localhost:3306/full_stack_db
    username: root
    password: rama123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # validate | update | create | create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
